import { Estado, TipoUsuario } from "@prisma/client";
export const perfil = [
    //Usuarios
    { identificacion: "1056789012", nombre: "Ana", apellido1: "Rodríguez", apellido2: "Vázquez", telefono: "81012345", correo: "ana.rodriguez@educaciononline.net", clave: "123456", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1067890123", nombre: "José", apellido1: "Martínez", apellido2: "García", telefono: "81987654", correo: "jose.martinez@educaciononline.net",clave: "246802", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1078901234", nombre: "Marta", apellido1: "Sánchez", apellido2: "Hernández", telefono: "81876543", correo: "marta.sanchez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1089012345", nombre: "Ricardo", apellido1: "Torres", apellido2: "Ramírez", telefono: "81765432", correo: "ricardo.torres@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1090123456", nombre: "Patricia", apellido1: "Pérez", apellido2: "Díaz", telefono: "81654321", correo: "patricia.perez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1101234567", nombre: "Luis", apellido1: "García", apellido2: "Fernández", telefono: "81543210", correo: "luis.garcia@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1112345678", nombre: "Beatriz", apellido1: "González", apellido2: "Lopez", telefono: "81432109", correo: "beatriz.gonzalez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1123456789", nombre: "Juan", apellido1: "Jiménez", apellido2: "Mendoza", telefono: "81321098", correo: "juan.jimenez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1134567890", nombre: "Isabel", apellido1: "Hernández", apellido2: "Martín", telefono: "81210987", correo: "isabel.hernandez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1145678901", nombre: "Fernando", apellido1: "Serrano", apellido2: "Romero", telefono: "81109876", correo: "fernando.serrano@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1156789012", nombre: "Ángela", apellido1: "Vázquez", apellido2: "Ruiz", telefono: "81098765", correo: "angela.vazquez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1167890123", nombre: "Pablo", apellido1: "Santos", apellido2: "Torres", telefono: "81987654", correo: "pablo.santos@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1178901234", nombre: "Eva", apellido1: "Martínez", apellido2: "González", telefono: "81876543", correo: "eva.martinez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1189012345", nombre: "Rafael", apellido1: "Pérez", apellido2: "Gómez", telefono: "81765432", correo: "rafael.perez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1190123456", nombre: "Lucía", apellido1: "Alonso", apellido2: "Fernández", telefono: "81654321", correo: "lucia.alonso@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1201234567", nombre: "David", apellido1: "Ramírez", apellido2: "García", telefono: "81543210", correo: "david.ramirez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1212345678", nombre: "Carmen", apellido1: "Gómez", apellido2: "Lopez", telefono: "81432109", correo: "carmen.gomez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1223456789", nombre: "Santiago", apellido1: "Torres", apellido2: "Martínez", telefono: "81321098", correo: "santiago.torres@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1234567890", nombre: "María", apellido1: "Serrano", apellido2: "Romero", telefono: "81210987", correo: "maria.serrano@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1245678901", nombre: "Juan", apellido1: "Vázquez", apellido2: "González", telefono: "81109876", correo: "juan.vazquez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1256789012", nombre: "Carla", apellido1: "Mendoza", apellido2: "Martín", telefono: "81098765", correo: "carla.mendoza@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1267890123", nombre: "Miguel", apellido1: "Romero", apellido2: "Santos", telefono: "81987654", correo: "miguel.romero@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1278901234", nombre: "Ana", apellido1: "Alonso", apellido2: "Martínez", telefono: "81876543", correo: "ana.alonso@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario } ,
    { identificacion: "1289012345", nombre: "Roberto", apellido1: "Ramírez", apellido2: "Gómez", telefono: "81765432", correo: "roberto.ramirez@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1290123456", nombre: "Paula", apellido1: "Pérez", apellido2: "Hernández", telefono: "81654321", correo: "paula.perez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1301234567", nombre: "Álvaro", apellido1: "Martínez", apellido2: "Vázquez", telefono: "81543210", correo: "alvaro.martinez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1312345678", nombre: "Lorena", apellido1: "Torres", apellido2: "Serrano", telefono: "81432109", correo: "lorena.torres@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1323456789", nombre: "Javier", apellido1: "González", apellido2: "Mendoza", telefono: "81321098", correo: "javier.gonzalez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1334567890", nombre: "Patricia", apellido1: "Hernández", apellido2: "Ramírez", telefono: "81210987", correo: "patricia.hernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1345678901", nombre: "Ricardo", apellido1: "Romero", apellido2: "Torres", telefono: "81109876", correo: "ricardo.romero@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1356789012", nombre: "Antonio", apellido1: "Gómez", apellido2: "Alonso", telefono: "81098765", correo: "antonio.gomez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1367890123", nombre: "Mónica", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "81987654", correo: "monica.vazquez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1378901234", nombre: "Carlos", apellido1: "Serrano", apellido2: "Mendoza", telefono: "81876543", correo: "carlos.serrano@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1389012345", nombre: "Laura", apellido1: "Romero", apellido2: "Gómez", telefono: "81765432", correo: "laura.romero@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1390123456", nombre: "Pedro", apellido1: "Pérez", apellido2: "Hernández", telefono: "81654321", correo: "pedro.perez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1401234567", nombre: "Antonio", apellido1: "Martínez", apellido2: "Torres", telefono: "81543210", correo: "antonio.martinez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1412345678", nombre: "Mercedes", apellido1: "Serrano", apellido2: "Vázquez", telefono: "81432109", correo: "mercedes.serrano@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1423456789", nombre: "Juan", apellido1: "Gómez", apellido2: "Romero", telefono: "81321098", correo: "juan.gomez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1434567890", nombre: "Beatriz", apellido1: "Ramírez", apellido2: "Serrano", telefono: "81210987", correo: "beatriz.ramirez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1445678901", nombre: "Rosa", apellido1: "Alonso", apellido2: "Martínez", telefono: "81109876", correo: "rosa.alonso@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1456789012", nombre: "Héctor", apellido1: "Pérez", apellido2: "González", telefono: "81098765", correo: "hector.perez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1467890123", nombre: "Sofía", apellido1: "Martínez", apellido2: "Alonso", telefono: "81987654", correo: "sofia.martinez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1478901234", nombre: "Luis", apellido1: "Gómez", apellido2: "Vázquez", telefono: "81876543", correo: "luis.gomez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1489012345", nombre: "María", apellido1: "Torres", apellido2: "Romero", telefono: "81765432", correo: "maria.torres@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1490123456", nombre: "José", apellido1: "Hernández", apellido2: "Gómez", telefono: "81654321", correo: "jose.hernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1501234567", nombre: "Andrea", apellido1: "Fernández", apellido2: "López", telefono: "81543210", correo: "andrea.fernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1512345678", nombre: "Manuel", apellido1: "Santos", apellido2: "Ramírez", telefono: "81432109", correo: "manuel.santos@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1523456789", nombre: "Elena", apellido1: "García", apellido2: "Martínez", telefono: "81321098", correo: "elena.garcia@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1534567890", nombre: "Raúl", apellido1: "Pérez", apellido2: "Sánchez", telefono: "81210987", correo: "raul.perez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1545678901", nombre: "Valeria", apellido1: "Vázquez", apellido2: "Gómez", telefono: "81109876", correo: "valeria.vazquez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1556789012", nombre: "Emilio", apellido1: "Romero", apellido2: "Torres", telefono: "81098765", correo: "emilio.romero@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1567890123", nombre: "Claudia", apellido1: "Hernández", apellido2: "Fernández", telefono: "81987654", correo: "claudia.hernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1578901234", nombre: "Daniel", apellido1: "Gómez", apellido2: "Pérez", telefono: "81876543", correo: "daniel.gomez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1589012345", nombre: "Verónica", apellido1: "Martínez", apellido2: "Ramírez", telefono: "81765432", correo: "veronica.martinez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1590123456", nombre: "Joaquín", apellido1: "Serrano", apellido2: "García", telefono: "81654321", correo: "joaquin.serrano@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1601234567", nombre: "Natalia", apellido1: "Torres", apellido2: "Hernández", telefono: "81543210", correo: "natalia.torres@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1612345678", nombre: "Adrián", apellido1: "González", apellido2: "Santos", telefono: "81432109", correo: "adrian.gonzalez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1623456789", nombre: "Silvia", apellido1: "Pérez", apellido2: "Vázquez", telefono: "81321098", correo: "silvia.perez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1634567890", nombre: "Francisco", apellido1: "Jiménez", apellido2: "Alonso", telefono: "81210987", correo: "francisco.jimenez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1645678901", nombre: "Luciano", apellido1: "Ramírez", apellido2: "Gómez", telefono: "81109876", correo: "luciano.ramirez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1656789012", nombre: "Gabriela", apellido1: "Hernández", apellido2: "Martínez", telefono: "81098765", correo: "gabriela.hernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1667890123", nombre: "Marcos", apellido1: "Fernández", apellido2: "Sánchez", telefono: "81987654", correo: "marcos.fernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1678901234", nombre: "Susana", apellido1: "García", apellido2: "Santos", telefono: "81876543", correo: "susana.garcia@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1689012345", nombre: "Hugo", apellido1: "Vázquez", apellido2: "Romero", telefono: "81765432", correo: "hugo.vazquez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1690123456", nombre: "Victoria", apellido1: "Gómez", apellido2: "Jiménez", telefono: "81654321", correo: "victoria.gomez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1501234567", nombre: "Elena", apellido1: "Ruiz", apellido2: "Martínez", telefono: "81543210", correo: "elena.ruiz@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1512345678", nombre: "Gonzalo", apellido1: "Fernández", apellido2: "García", telefono: "81432109", correo: "gonzalo.fernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1523456789", nombre: "Cecilia", apellido1: "Díaz", apellido2: "Serrano", telefono: "81321098", correo: "cecilia.diaz@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1534567890", nombre: "Esteban", apellido1: "Jiménez", apellido2: "Alonso", telefono: "81210987", correo: "esteban.jimenez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1545678901", nombre: "Natalia", apellido1: "Vargas", apellido2: "Mendoza", telefono: "81109876", correo: "natalia.vargas@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1556789012", nombre: "Oscar", apellido1: "Román", apellido2: "López", telefono: "81098765", correo: "oscar.roman@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1567890123", nombre: "Silvia", apellido1: "Herrera", apellido2: "Gutiérrez", telefono: "81987654", correo: "silvia.herrera@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1578901234", nombre: "Hugo", apellido1: "Muñoz", apellido2: "Ramírez", telefono: "81876543", correo: "hugo.munoz@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1589012345", nombre: "Andrea", apellido1: "Reyes", apellido2: "Pérez", telefono: "81765432", correo: "andrea.reyes@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1590123456", nombre: "Fabián", apellido1: "Santos", apellido2: "Gómez", telefono: "81654321", correo: "fabian.santos@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1601234567", nombre: "Daniela", apellido1: "Morales", apellido2: "Vázquez", telefono: "81543210", correo: "daniela.morales@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1612345678", nombre: "Rodrigo", apellido1: "Ortega", apellido2: "Torres", telefono: "81432109", correo: "rodrigo.ortega@educaciononline.net", estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1623456789", nombre: "Valeria", apellido1: "Navarro", apellido2: "Fernández", telefono: "81321098", correo: "valeria.navarro@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1634567890", nombre: "Emilio", apellido1: "Guerrero", apellido2: "Martínez", telefono: "81210987", correo: "emilio.guerrero@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1645678901", nombre: "Gabriela", apellido1: "Castro", apellido2: "Hernández", telefono: "81109876", correo: "gabriela.castro@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1656789012", nombre: "Sergio", apellido1: "Vega", apellido2: "García", telefono: "81098765", correo: "sergio.vega@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1667890123", nombre: "Luciana", apellido1: "Méndez", apellido2: "Díaz", telefono: "81987654", correo: "luciana.mendez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1678901234", nombre: "Fernando", apellido1: "Lorenzo", apellido2: "Jiménez", telefono: "81876543", correo: "fernando.lorenzo@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1689012345", nombre: "Alicia", apellido1: "Cortés", apellido2: "Ramírez", telefono: "81765432", correo: "alicia.cortes@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1690123456", nombre: "Joaquín", apellido1: "Salas", apellido2: "Santos", telefono: "81654321", correo: "joaquin.salas@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1701234567", nombre: "Camila", apellido1: "Hernández", apellido2: "López", telefono: "81543210", correo: "camila.hernandez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1712345678", nombre: "Diego", apellido1: "Soto", apellido2: "Fernández", telefono: "81432109", correo: "diego.soto@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1723456789", nombre: "Mariana", apellido1: "Gómez", apellido2: "Ramírez", telefono: "81321098", correo: "mariana.gomez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1734567890", nombre: "Bruno", apellido1: "Delgado", apellido2: "Torres", telefono: "81210987", correo: "bruno.delgado@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1745678901", nombre: "Isabella", apellido1: "Ríos", apellido2: "Vargas", telefono: "81109876", correo: "isabella.rios@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1756789012", nombre: "Pablo", apellido1: "Montoya", apellido2: "Navarro", telefono: "81098765", correo: "pablo.montoya@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1767890123", nombre: "Lucía", apellido1: "Figueroa", apellido2: "Castillo", telefono: "81987654", correo: "lucia.figueroa@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1778901234", nombre: "Javier", apellido1: "Cárdenas", apellido2: "Gutiérrez", telefono: "81876543", correo: "javier.cardenas@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1789012345", nombre: "Sofía", apellido1: "Peña", apellido2: "Mendoza", telefono: "81765432", correo: "sofia.pena@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1790123456", nombre: "Matías", apellido1: "Campos", apellido2: "Ortega", telefono: "81654321", correo: "matias.campos@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1801234567", nombre: "Renata", apellido1: "Cruz", apellido2: "Muñoz", telefono: "81543210", correo: "renata.cruz@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1812345678", nombre: "Felipe", apellido1: "Álvarez", apellido2: "Jiménez", telefono: "81432109", correo: "felipe.alvarez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1823456789", nombre: "Alejandra", apellido1: "Suárez", apellido2: "Duarte", telefono: "81321098", correo: "alejandra.suarez@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1834567890", nombre: "Emiliano", apellido1: "Vega", apellido2: "Paredes", telefono: "81210987", correo: "emiliano.vega@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
    { identificacion: "1845678901", nombre: "Valeria", apellido1: "Lara", apellido2: "Esquivel", telefono: "81109876", correo: "valeria.lara@educaciononline.net",estado: Estado.Activo, tipoUsuario: TipoUsuario.Usuario },
        
    //   //Docentes
    { identificacion: "3061234567", nombre: "Laura", apellido1: "Jiménez", apellido2: "Sánchez", telefono: "81765432", correo: "laura.jimenez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5012345678", nombre: "Ricardo", apellido1: "Torres", apellido2: "González", telefono: "81654321", correo: "ricardo.torres@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034567890", nombre: "Marta", apellido1: "Ramírez", apellido2: "Serrano", telefono: "81543210", correo: "marta.ramirez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4023456789", nombre: "José", apellido1: "Pérez", apellido2: "Martínez", telefono: "81432109", correo: "jose.perez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5067890123", nombre: "Lucía", apellido1: "Gómez", apellido2: "Alonso", telefono: "81321098", correo: "lucia.gomez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7039876543", nombre: "Santiago", apellido1: "González", apellido2: "Torres", telefono: "81210987", correo: "santiago.gonzalez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6034567890", nombre: "Ana", apellido1: "Sánchez", apellido2: "Martínez", telefono: "81109876", correo: "ana.sanchez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2045678901", nombre: "Carlos", apellido1: "Vázquez", apellido2: "Romero", telefono: "81098765", correo: "carlos.vazquez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "1076543210", nombre: "Pablo", apellido1: "Serrano", apellido2: "Jiménez", telefono: "81987654", correo: "pablo.serrano@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "3023456789", nombre: "Juan", apellido1: "Martínez", apellido2: "Gómez", telefono: "81876543", correo: "juan.martinez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6045678901", nombre: "Rosa", apellido1: "Torres", apellido2: "Pérez", telefono: "81765432", correo: "rosa.torres@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6012345678", nombre: "José", apellido1: "Alonso", apellido2: "Vázquez", telefono: "81654321", correo: "jose.alonso@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7056789012", nombre: "Ana", apellido1: "Romero", apellido2: "Serrano", telefono: "81543210", correo: "ana.romero@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2034567890", nombre: "Carlos", apellido1: "Pérez", apellido2: "Hernández", telefono: "81432109", correo: "carlos.perez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5067890123", nombre: "Isabel", apellido1: "Vázquez", apellido2: "Torres", telefono: "81321098", correo: "isabel.vazquez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2078901234", nombre: "David", apellido1: "Ramírez", apellido2: "Pérez", telefono: "81210987", correo: "david.ramirez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "3045678901", nombre: "Carmen", apellido1: "Martínez", apellido2: "Romero", telefono: "81109876", correo: "carmen.martinez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "1067890123", nombre: "Rafael", apellido1: "Torres", apellido2: "Vázquez", telefono: "81098765", correo: "rafael.torres@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5061234567", nombre: "Laura", apellido1: "González", apellido2: "Serrano", telefono: "81987654", correo: "laura.gonzalez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7012345678", nombre: "José", apellido1: "Gómez", apellido2: "Vázquez", telefono: "81876543", correo: "jose.gomez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7065432109", nombre: "Sandra", apellido1: "Martínez", apellido2: "Romero", telefono: "81765432", correo: "sandra.martinez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6078901234", nombre: "Juan", apellido1: "Vázquez", apellido2: "González", telefono: "81654321", correo: "juan.vazquez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "1045678901", nombre: "Raquel", apellido1: "Torres", apellido2: "Jiménez", telefono: "81543210", correo: "raquel.torres@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7023456789", nombre: "Álvaro", apellido1: "Gómez", apellido2: "Hernández", telefono: "81432109", correo: "alvaro.gomez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "3034567890", nombre: "Cristina", apellido1: "Serrano", apellido2: "Alonso", telefono: "81321098", correo: "cristina.serrano@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5067890123", nombre: "Javier", apellido1: "González", apellido2: "Ramírez", telefono: "81210987", correo: "javier.gonzalez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6045678901", nombre: "Sofia", apellido1: "Vázquez", apellido2: "Torres", telefono: "81109876", correo: "sofia.vazquez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034567890", nombre: "Carlos", apellido1: "Pérez", apellido2: "Romero", telefono: "81098765", correo: "carlos.perezRomero@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2023456789", nombre: "José", apellido1: "Romero", apellido2: "Torres", telefono: "81987654", correo: "jose.romero@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7012345678", nombre: "Beatriz", apellido1: "Vázquez", apellido2: "Martínez", telefono: "81876543", correo: "beatriz.vazquez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4056789012", nombre: "David", apellido1: "Hernández", apellido2: "Serrano", telefono: "81765432", correo: "david.hernandez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6045678901", nombre: "Raúl", apellido1: "Pérez", apellido2: "González", telefono: "81654321", correo: "raul.perez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5067890123", nombre: "Mónica", apellido1: "Alonso", apellido2: "Martínez", telefono: "81543210", correo: "monica.alonso@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2034567890", nombre: "Manuel", apellido1: "Torres", apellido2: "Serrano", telefono: "81432109", correo: "manuel.torres@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7056789012", nombre: "Lucía", apellido1: "Ramírez", apellido2: "Vázquez", telefono: "81321098", correo: "lucia.ramirez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "1045678901", nombre: "Paola", apellido1: "Serrano", apellido2: "Martínez", telefono: "81210987", correo: "paola.serrano@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "3023456789", nombre: "Javier", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "81109876", correo: "javier.vazquez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4045678901", nombre: "Pedro", apellido1: "Torres", apellido2: "Alonso", telefono: "81098765", correo: "pedro.torres@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6056789012", nombre: "Andrea", apellido1: "Martínez", apellido2: "Romero", telefono: "81987654", correo: "andrea.martinez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034567890", nombre: "Sofia", apellido1: "Hernández", apellido2: "Pérez", telefono: "81876543", correo: "sofia.hernandez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2045678901", nombre: "Jorge", apellido1: "Gómez", apellido2: "Torres", telefono: "81765432", correo: "jorge.gomez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "3056789012", nombre: "Mercedes", apellido1: "Serrano", apellido2: "Martínez", telefono: "81654321", correo: "mercedes.serrano@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "9076543210", nombre: "Antonio", apellido1: "Sánchez", apellido2: "Vázquez", telefono: "81912345", correo: "antonio.sanchez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "8098765432", nombre: "Carlos", apellido1: "González", apellido2: "Ramírez", telefono: "81823456", correo: "carlos.gonzalez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "9087654321", nombre: "Ana", apellido1: "Gómez", apellido2: "Alonso", telefono: "81734567", correo: "ana.gomez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7076543210", nombre: "Pedro", apellido1: "Hernández", apellido2: "Serrano", telefono: "81645678", correo: "pedro.hernandez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6065432109", nombre: "Laura", apellido1: "Vázquez", apellido2: "Torres", telefono: "81556789", correo: "laura.vazquez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7077654321", nombre: "José", apellido1: "Martínez", apellido2: "Gómez", telefono: "81467890", correo: "jose.martinez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5087654321", nombre: "Marta", apellido1: "González", apellido2: "Romero", telefono: "81378901", correo: "marta.gonzalez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6098765432", nombre: "Rafael", apellido1: "Pérez", apellido2: "Vázquez", telefono: "81289012", correo: "rafael.perez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "8012345678", nombre: "Cristina", apellido1: "Alonso", apellido2: "Serrano", telefono: "81190123", correo: "cristina.alonso01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7039876543", nombre: "Carmen", apellido1: "Romero", apellido2: "Torres", telefono: "81091234", correo: "carmen.romero01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5034567890", nombre: "Juan", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "80902345", correo: "juan.vazquez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4098765432", nombre: "Lucía", apellido1: "Torres", apellido2: "Pérez", telefono: "80813456", correo: "lucia.torres01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6045678901", nombre: "Javier", apellido1: "Romero", apellido2: "Serrano", telefono: "80724567", correo: "javier.romero01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034567890", nombre: "José", apellido1: "Serrano", apellido2: "Vázquez", telefono: "80635678", correo: "jose.serrano01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6056789012", nombre: "Paola", apellido1: "Gómez", apellido2: "Hernández", telefono: "80546789", correo: "paola.gomez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5076543210", nombre: "Sandra", apellido1: "Torres", apellido2: "Ramírez", telefono: "80457890", correo: "sandra.torres01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7045678901", nombre: "Raúl", apellido1: "González", apellido2: "Alonso", telefono: "80368901", correo: "raul.gonzalez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6054321098", nombre: "David", apellido1: "Ramírez", apellido2: "Torres", telefono: "80279012", correo: "david.ramirez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5074321098", nombre: "María", apellido1: "Martínez", apellido2: "Gómez", telefono: "80190123", correo: "maria.martinez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4035678901", nombre: "Beatriz", apellido1: "Romero", apellido2: "González", telefono: "80001234", correo: "beatriz.romero01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7031234567", nombre: "Juan", apellido1: "Gómez", apellido2: "Vázquez", telefono: "81998765", correo: "juan.gomez02@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6078901234", nombre: "Alba", apellido1: "Alonso", apellido2: "Ramírez", telefono: "81887654", correo: "alba.alonso01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7065432109", nombre: "Felipe", apellido1: "Vázquez", apellido2: "Romero", telefono: "81776543", correo: "felipe.vazquez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6076543210", nombre: "Sonia", apellido1: "Serrano", apellido2: "Pérez", telefono: "81665432", correo: "sonia.serrano01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5067890123", nombre: "Rosa", apellido1: "Martínez", apellido2: "Torres", telefono: "81554321", correo: "rosa.martinez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034567890", nombre: "Álvaro", apellido1: "Romero", apellido2: "Sánchez", telefono: "81443210", correo: "alvaro.romero01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4023456789", nombre: "Inés", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "81332109", correo: "ines.vazquez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034564490", nombre: "Sofia", apellido1: "Hernández", apellido2: "Pérez", telefono: "81876543", correo: "sofia.hernand4ez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2041178901", nombre: "Jorge", apellido1: "Gómez", apellido2: "Torres", telefono: "81765432", correo: "jorge.gom4ez@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "3051189012", nombre: "Mercedes", apellido1: "Serrano", apellido2: "Martínez", telefono: "81654321", correo: "mer4cedes.serrano@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "9076223210", nombre: "Antonio", apellido1: "Sánchez", apellido2: "Vázquez", telefono: "81912345", correo: "anto4nio.sanchez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2222222222", nombre: "Carlos", apellido1: "González", apellido2: "Ramírez", telefono: "81823456", correo: "car4los.gonzalez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "1111111111", nombre: "Ana", apellido1: "Gómez", apellido2: "Alonso", telefono: "81734567", correo: "ana.gomez401@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5555555555", nombre: "Pedro", apellido1: "Hernández", apellido2: "Serrano", telefono: "81645678", correo: "pedro.hernandez401@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7990090900", nombre: "Laura", apellido1: "Vázquez", apellido2: "Torres", telefono: "81556789", correo: "laura.vazquez041@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7077654321", nombre: "José", apellido1: "Martínez", apellido2: "Gómez", telefono: "81467890", correo: "jose.martinez07871@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "2468024677", nombre: "Marta", apellido1: "González", apellido2: "Romero", telefono: "81378901", correo: "marta.gonzalez401@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "1122334455", nombre: "Rafael", apellido1: "Pérez", apellido2: "Vázquez", telefono: "81289012", correo: "rafael.perez501@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "8012345678", nombre: "Cristina", apellido1: "Alonso", apellido2: "Serrano", telefono: "81190123", correo: "cristina.alonso501@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7039876543", nombre: "Carmen", apellido1: "Romero", apellido2: "Torres", telefono: "81091234", correo: "carmen.romero041@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5034567890", nombre: "Juan", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "80902345", correo: "juan.vazquez031@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4098765432", nombre: "Lucía", apellido1: "Torres", apellido2: "Pérez", telefono: "80813456", correo: "lucia.torres031@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6045678901", nombre: "Javier", apellido1: "Romero", apellido2: "Serrano", telefono: "80724567", correo: "javier.romer4o01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034567890", nombre: "José", apellido1: "Serrano", apellido2: "Vázquez", telefono: "80635678", correo: "jose.serrano051@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6056789012", nombre: "Paola", apellido1: "Gómez", apellido2: "Hernández", telefono: "80546789", correo: "paola.gomez041@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5076543210", nombre: "Sandra", apellido1: "Torres", apellido2: "Ramírez", telefono: "80457890", correo: "sandra.torres014@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7045678901", nombre: "Raúl", apellido1: "González", apellido2: "Alonso", telefono: "80368901", correo: "raul.gonzalez041@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6054321098", nombre: "David", apellido1: "Ramírez", apellido2: "Torres", telefono: "80279012", correo: "david.4@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5074321098", nombre: "María", apellido1: "Martínez", apellido2: "Gómez", telefono: "80190123", correo: "maria.mart4inez01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4035678901", nombre: "Beatriz", apellido1: "Romero", apellido2: "González", telefono: "80001234", correo: "beatri4z.romero01@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7031234567", nombre: "Juan", apellido1: "Gómez", apellido2: "Vázquez", telefono: "81998765", correo: "juan.gomez04@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6078901234", nombre: "Alba", apellido1: "Alonso", apellido2: "Ramírez", telefono: "81887654", correo: "alba.alonso0144@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7065432109", nombre: "Felipe", apellido1: "Vázquez", apellido2: "Romero", telefono: "81776543", correo: "felipe.vazquez4401@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "6076543210", nombre: "Sonia", apellido1: "Serrano", apellido2: "Pérez", telefono: "81665432", correo: "sonia.serrano0155@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "5067890123", nombre: "Rosa", apellido1: "Martínez", apellido2: "Torres", telefono: "81554321", correo: "rosa.martinez0551@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "7034567890", nombre: "Álvaro", apellido1: "Romero", apellido2: "Sánchez", telefono: "81443210", correo: "alvaro.romero501@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4023456789", nombre: "Inés", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "81332109", correo: "ines.vazquez05551@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4023456789", nombre: "Juan", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "81332109", correo: "juan2000.vazquez05551@docente.net", tipoUsuario: TipoUsuario.Docente },
    { identificacion: "4023456789", nombre: "Pablo", apellido1: "Vázquez", apellido2: "Ramírez", telefono: "81332109", correo: "pabblo33.vazquez05551@docente.net", tipoUsuario: TipoUsuario.Docente },
    
    
    //     //Estudiantes
    { identificacion: "1012345678", nombre: "Juan", apellido1: "Pérez", apellido2: "González", telefono: "81234567", correo: "juan.perez@estudiante.com", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "1023456789", nombre: "Ana", apellido1: "Sánchez", apellido2: "Lopez", telefono: "81345678", correo: "ana.sanchezlopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "2012345678", nombre: "Carlos", apellido1: "Martínez", apellido2: "Ramírez", telefono: "81456789", correo: "carlos.martinezramirez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "3023456789", nombre: "Laura", apellido1: "Hernández", apellido2: "Serrano", telefono: "81567890", correo: "laura.hernandez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "5034567890", nombre: "David", apellido1: "Gómez", apellido2: "Alvarez", telefono: "81678901", correo: "david.gomez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "6017890123", nombre: "Patricia", apellido1: "López", apellido2: "Fernández", telefono: "81789012", correo: "patricia.lopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "2045678901", nombre: "Javier", apellido1: "Ruiz", apellido2: "Jiménez", telefono: "81890123", correo: "javier.ruiz@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7056789012", nombre: "Beatriz", apellido1: "Alvarez", apellido2: "García", telefono: "81901234", correo: "beatriz.alvarez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "1034567890", nombre: "Fernando", apellido1: "Rodríguez", apellido2: "Vázquez", telefono: "82012345", correo: "fernando.rodriguez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "2021234567", nombre: "Carmen", apellido1: "Torres", apellido2: "Martínez", telefono: "82123456", correo: "carmen.torres@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "1015678901", nombre: "Raúl", apellido1: "Núñez", apellido2: "Sánchez", telefono: "82234567", correo: "raul.nunez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "5036789012", nombre: "Verónica", apellido1: "López", apellido2: "Pérez", telefono: "82345678", correo: "veronica.lopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "3057890123", nombre: "José", apellido1: "Morales", apellido2: "López", telefono: "82456789", correo: "jose.morales@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "4034567890", nombre: "Marta", apellido1: "Ramírez", apellido2: "García", telefono: "82567890", correo: "marta.ramirez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "6045678901", nombre: "Pablo", apellido1: "Sánchez", apellido2: "Martín", telefono: "82678901", correo: "pablo.sanchez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7017890123", nombre: "Laura", apellido1: "Torres", apellido2: "González", telefono: "82789012", correo: "laura.torres@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "4023456789", nombre: "Javier", apellido1: "Álvarez", apellido2: "Serrano", telefono: "82890123", correo: "javier.alvarez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "3056789012", nombre: "Susana", apellido1: "Vázquez", apellido2: "Ruiz", telefono: "82901234", correo: "susana.vazquez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7045678901", nombre: "Alberto", apellido1: "Ramírez", apellido2: "Jiménez", telefono: "83012345", correo: "alberto.ramirez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "5036789012", nombre: "María", apellido1: "Hernández", apellido2: "Pérez", telefono: "83123456", correo: "maria.hernandez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "5012345678", nombre: "Miguel", apellido1: "Sánchez", apellido2: "González", telefono: "83234567", correo: "miguel.sanchez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "6012345678", nombre: "Luis", apellido1: "Pérez", apellido2: "Fernández", telefono: "83345678", correo: "luis.perez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7034567890", nombre: "Elena", apellido1: "Morales", apellido2: "García", telefono: "83456789", correo: "elena.morales@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7045678901", nombre: "Ricardo", apellido1: "Ruiz", apellido2: "Álvarez", telefono: "83567890", correo: "ricardo.ruiz@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "6012345678", nombre: "José", apellido1: "Ramírez", apellido2: "Sánchez", telefono: "83789012", correo: "jose.ramirez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7045678901", nombre: "Sara", apellido1: "Alonso", apellido2: "Morales", telefono: "83890123", correo: "sara.alonso@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7056789012", nombre: "Pedro", apellido1: "Méndez", apellido2: "López", telefono: "83901234", correo: "pedro.mendez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "3036789012", nombre: "Carla", apellido1: "Cordero", apellido2: "González", telefono: "84012345", correo: "carla.cordero@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "4037890123", nombre: "Laura", apellido1: "Martínez", apellido2: "Rodríguez", telefono: "84123456", correo: "laura.martinez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7012345678", nombre: "David", apellido1: "Sánchez", apellido2: "Pérez", telefono: "84234567", correo: "david.sanchez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "6045678901", nombre: "Daniel", apellido1: "Torres", apellido2: "Cortes", telefono: "84345678", correo: "daniel.torres@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "6023456789", nombre: "Nerea", apellido1: "Gómez", apellido2: "Ramírez", telefono: "84456789", correo: "nerea.gomez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "1023456789", nombre: "Raúl", apellido1: "Martín", apellido2: "Ruiz", telefono: "84567890", correo: "raul.martin@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "1067890123", nombre: "Juan", apellido1: "Alonso", apellido2: "Fernández", telefono: "84678901", correo: "juan.alonso@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "6037890123", nombre: "Antonio", apellido1: "Álvarez", apellido2: "Pérez", telefono: "84789012", correo: "antonio.alvarez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "7034567890", nombre: "Mónica", apellido1: "Pérez", apellido2: "González", telefono: "84890123", correo: "monica.perez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "3023456789", nombre: "Julia", apellido1: "López", apellido2: "Serrano", telefono: "84901234", correo: "julia.lopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8056789012", nombre: "Sofía", apellido1: "García", apellido2: "López", telefono: "85012345", correo: "sofia.garcia@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "9023456789", nombre: "Andrés", apellido1: "Fernández", apellido2: "Martínez", telefono: "85123456", correo: "andres.fernandez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "9012345678", nombre: "Clara", apellido1: "Ramírez", apellido2: "Torres", telefono: "85234567", correo: "clara.ramirez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8034567890", nombre: "Hugo", apellido1: "Vázquez", apellido2: "Sánchez", telefono: "85345678", correo: "hugo.vazquez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8023456789", nombre: "Isabel", apellido1: "Alonso", apellido2: "Gómez", telefono: "85456789", correo: "isabel.alonso@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "9056789012", nombre: "Manuel", apellido1: "Serrano", apellido2: "Pérez", telefono: "85567890", correo: "manuel.serrano@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8067890123", nombre: "Teresa", apellido1: "Cordero", apellido2: "Morales", telefono: "85678901", correo: "teresa.cordero@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8078901234", nombre: "Gabriel", apellido1: "Jiménez", apellido2: "Ruiz", telefono: "85789012", correo: "gabriel.jimenez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8089012345", nombre: "Rocío", apellido1: "López", apellido2: "Álvarez", telefono: "85890123", correo: "rocio.lopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8090123456", nombre: "Emilio", apellido1: "Sánchez", apellido2: "Hernández", telefono: "85901234", correo: "emilio.sanchez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8101234567", nombre: "Natalia", apellido1: "Gómez", apellido2: "Serrano", telefono: "86012345", correo: "natalia.gomez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8112345678", nombre: "Esteban", apellido1: "Ramírez", apellido2: "López", telefono: "86123456", correo: "esteban.ramirez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8123456789", nombre: "Lucía", apellido1: "Fernández", apellido2: "Torres", telefono: "86234567", correo: "lucia.fernandez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8134567890", nombre: "Marcos", apellido1: "Álvarez", apellido2: "Morales", telefono: "86345678", correo: "marcos.alvarez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8145678901", nombre: "Silvia", apellido1: "Rodríguez", apellido2: "Martínez", telefono: "86456789", correo: "silvia.rodriguez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8156789012", nombre: "Óscar", apellido1: "Sánchez", apellido2: "Vázquez", telefono: "86567890", correo: "oscar.sanchez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8167890123", nombre: "Daniela", apellido1: "Cordero", apellido2: "Jiménez", telefono: "86678901", correo: "daniela.cordero@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8178901234", nombre: "Joaquín", apellido1: "Núñez", apellido2: "Pérez", telefono: "86789012", correo: "joaquin.nunez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8189012345", nombre: "Irene", apellido1: "López", apellido2: "Hernández", telefono: "86890123", correo: "irene.lopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8190123456", nombre: "Héctor", apellido1: "Ruiz", apellido2: "García", telefono: "86901234", correo: "hector.ruiz@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8201234567", nombre: "Camila", apellido1: "Martínez", apellido2: "Ramírez", telefono: "87012345", correo: "camila.martinez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8212345678", nombre: "Santiago", apellido1: "Pérez", apellido2: "Álvarez", telefono: "87123456", correo: "santiago.perez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8223456789", nombre: "Eva", apellido1: "Serrano", apellido2: "Torres", telefono: "87234567", correo: "eva.serrano@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8234567890", nombre: "Felipe", apellido1: "Gómez", apellido2: "Fernández", telefono: "87345678", correo: "felipe.gomez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8245678901", nombre: "Miriam", apellido1: "López", apellido2: "Martínez", telefono: "87456789", correo: "miriam.lopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8256789012", nombre: "Ramón", apellido1: "Hernández", apellido2: "Rodríguez", telefono: "87567890", correo: "ramon.hernandez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8267890123", nombre: "Beatriz", apellido1: "Vázquez", apellido2: "Cordero", telefono: "87678901", correo: "beatriz.vazquez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8278901234", nombre: "Tomás", apellido1: "Ruiz", apellido2: "Álvarez", telefono: "87789012", correo: "tomas.ruiz@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8289012345", nombre: "Lorena", apellido1: "Sánchez", apellido2: "Pérez", telefono: "87890123", correo: "lorena.sanchez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8290123456", nombre: "Ignacio", apellido1: "García", apellido2: "Ramírez", telefono: "87901234", correo: "ignacio.garcia@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8301234567", nombre: "Renata", apellido1: "Villalobos", apellido2: "Quirós", telefono: "88012345", correo: "renata.villalobos@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8312345678", nombre: "Julián", apellido1: "Camacho", apellido2: "Salazar", telefono: "88123456", correo: "julian.camacho@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8323456789", nombre: "Paula", apellido1: "Rojas", apellido2: "Méndez", telefono: "88234567", correo: "paula.rojas@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8334567890", nombre: "Mateo", apellido1: "Solano", apellido2: "Jiménez", telefono: "88345678", correo: "mateo.solano@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8345678901", nombre: "Mariana", apellido1: "Zamora", apellido2: "González", telefono: "88456789", correo: "mariana.zamora@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8356789012", nombre: "Elena", apellido1: "Ureña", apellido2: "Fernández", telefono: "88567890", correo: "elena.urena@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8367890123", nombre: "Gustavo", apellido1: "Navarro", apellido2: "López", telefono: "88678901", correo: "gustavo.navarro@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8378901234", nombre: "Patricia", apellido1: "Vargas", apellido2: "Morales", telefono: "88789012", correo: "patricia.vargas@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8389012345", nombre: "Rodrigo", apellido1: "León", apellido2: "Sánchez", telefono: "88890123", correo: "rodrigo.leon@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8390123456", nombre: "Andrea", apellido1: "Céspedes", apellido2: "Álvarez", telefono: "88901234", correo: "andrea.cespedes@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8401234567", nombre: "Sebastián", apellido1: "Gutiérrez", apellido2: "Ramírez", telefono: "89012345", correo: "sebastian.gutierrez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8412345678", nombre: "Valeria", apellido1: "Soto", apellido2: "Pérez", telefono: "89123456", correo: "valeria.soto@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8423456789", nombre: "Emilio", apellido1: "Barrantes", apellido2: "García", telefono: "89234567", correo: "emilio.barrantes@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8434567890", nombre: "Diana", apellido1: "Esquivel", apellido2: "Martínez", telefono: "89345678", correo: "diana.esquivel@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8445678901", nombre: "Mauricio", apellido1: "Chaves", apellido2: "Rodríguez", telefono: "89456789", correo: "mauricio.chaves@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8456789012", nombre: "Carla", apellido1: "Rojas", apellido2: "Jiménez", telefono: "89567890", correo: "carla.rojas@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8467890123", nombre: "Ricardo", apellido1: "Salas", apellido2: "Fernández", telefono: "89678901", correo: "ricardo.salas@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8478901234", nombre: "Sofía", apellido1: "Mora", apellido2: "Vásquez", telefono: "89789012", correo: "sofia.mora@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8489012345", nombre: "Leonardo", apellido1: "Zúñiga", apellido2: "Torres", telefono: "89890123", correo: "leonardo.zuniga@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8490123456", nombre: "Natalia", apellido1: "Delgado", apellido2: "Castro", telefono: "89901234", correo: "natalia.delgado@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8501234567", nombre: "Daniel", apellido1: "Méndez", apellido2: "Alvarado", telefono: "90012345", correo: "daniel.mendez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8512345678", nombre: "Lucía", apellido1: "Gómez", apellido2: "Ramírez", telefono: "90123456", correo: "lucia.gomez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8523456789", nombre: "Fernando", apellido1: "Araya", apellido2: "Gutiérrez", telefono: "90234567", correo: "fernando.araya@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8534567890", nombre: "Raquel", apellido1: "Solís", apellido2: "Vargas", telefono: "90345678", correo: "raquel.solis@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8545678901", nombre: "Cristian", apellido1: "Pacheco", apellido2: "Soto", telefono: "90456789", correo: "cristian.pacheco@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8556789012", nombre: "Tatiana", apellido1: "Herrera", apellido2: "León", telefono: "90567890", correo: "tatiana.herrera@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8567890123", nombre: "José", apellido1: "López", apellido2: "Monge", telefono: "90678901", correo: "jose.lopez@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8578901234", nombre: "Esteban", apellido1: "Valverde", apellido2: "Chávez", telefono: "90789012", correo: "esteban.valverde@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8589012345", nombre: "Gabriela", apellido1: "Muñoz", apellido2: "Castillo", telefono: "90890123", correo: "gabriela.munoz@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8590123456", nombre: "Héctor", apellido1: "Serrano", apellido2: "Lara", telefono: "90901234", correo: "hector.serrano@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8601234567", nombre: "Mónica", apellido1: "Chinchilla", apellido2: "Jiménez", telefono: "91012345", correo: "monica.chinchilla@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8612345678", nombre: "Pedro", apellido1: "Cordero", apellido2: "Sáenz", telefono: "91123456", correo: "pedro.cordero@estudiante.net", tipoUsuario: TipoUsuario.Estudiante },
    { identificacion: "8623456789", nombre: "Verónica", apellido1: "Arias", apellido2: "Gamboa", telefono: "91234567", correo: "veronica.arias@estudiante.net", tipoUsuario: TipoUsuario.Estudiante }


    ];